"""phase1 persistence

Revision ID: 4b4bdee9575a
Revises:
Create Date: 2026-10-02 22:53:34.819324
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4b4bdee9575a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("source_policy_id", sa.String(length=100), nullable=False),
        sa.Column("publisher_role", sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_url"),
    )
    op.create_table(
        "programmes",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("provider", sa.String(length=300), nullable=False),
        sa.Column("registry_version", sa.String(length=40), nullable=False),
        sa.Column("support_status", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_programmes_support_status"), "programmes", ["support_status"], unique=False
    )
    op.create_table(
        "worker_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=100), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "checks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("programme_id", sa.String(length=100), nullable=False),
        sa.Column("requested_scope_json", sa.JSON(), nullable=False),
        sa.Column("profile_json", sa.JSON(), nullable=True),
        sa.Column("notice_url", sa.Text(), nullable=True),
        sa.Column("saved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["programme_id"],
            ["programmes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_checks_expires_at"), "checks", ["expires_at"], unique=False)
    op.create_index(op.f("ix_checks_programme_id"), "checks", ["programme_id"], unique=False)
    op.create_table(
        "document_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("original_path", sa.Text(), nullable=False),
        sa.Column("parsed_blocks_path", sa.Text(), nullable=False),
        sa.Column("parser_version", sa.String(length=40), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parse_status", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "sha256", "parser_version", name="uq_document_version"),
    )
    op.create_table(
        "extractions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_version_id", sa.String(length=36), nullable=False),
        sa.Column("model_id", sa.String(length=200), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.Column("facts_json", sa.JSON(), nullable=False),
        sa.Column("validation_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_version_id",
            "model_id",
            "prompt_hash",
            "schema_version",
            name="uq_extraction_version",
        ),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("check_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("operation_scope", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("reference_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.Column("owner_token", sa.String(length=64), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_of_run_id", sa.String(length=36), nullable=True),
        sa.Column("version_manifest_json", sa.JSON(), nullable=True),
        sa.Column("usage_json", sa.JSON(), nullable=True),
        sa.Column("error_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["check_id"], ["checks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["retry_of_run_id"], ["runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operation_scope", "idempotency_key", name="uq_run_idempotency"),
    )
    op.create_index(op.f("ix_runs_status"), "runs", ["status"], unique=False)
    op.create_index("ix_runs_status_created_at", "runs", ["status", "created_at"], unique=False)
    op.create_index(
        "uq_runs_one_active_per_check",
        "runs",
        ["check_id"],
        unique=True,
        sqlite_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("report_schema_version", sa.String(length=40), nullable=False),
        sa.Column("decisions_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_table(
        "run_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("requested_url", sa.Text(), nullable=False),
        sa.Column("resolved_url", sa.Text(), nullable=True),
        sa.Column("document_version_id", sa.String(length=36), nullable=True),
        sa.Column("extraction_id", sa.String(length=36), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cache_provenance", sa.String(length=40), nullable=False),
        sa.Column("fetch_status", sa.String(length=40), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["extraction_id"], ["extractions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "requested_url", name="uq_run_document_url"),
    )
    op.create_table(
        "search_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("parameters_json", sa.JSON(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_search_id", sa.String(length=200), nullable=True),
        sa.Column("response_path", sa.Text(), nullable=True),
        sa.Column("local_cache_hit", sa.Boolean(), nullable=False),
        sa.Column("outcome", sa.String(length=40), nullable=False),
        sa.Column("usage_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_search_requests_run_id"), "search_requests", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_search_requests_run_id"), table_name="search_requests")
    op.drop_table("search_requests")
    op.drop_table("run_documents")
    op.drop_table("reports")
    op.drop_index(
        "uq_runs_one_active_per_check",
        table_name="runs",
        sqlite_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index("ix_runs_status_created_at", table_name="runs")
    op.drop_index(op.f("ix_runs_status"), table_name="runs")
    op.drop_table("runs")
    op.drop_table("extractions")
    op.drop_table("document_versions")
    op.drop_index(op.f("ix_checks_programme_id"), table_name="checks")
    op.drop_index(op.f("ix_checks_expires_at"), table_name="checks")
    op.drop_table("checks")
    op.drop_table("worker_state")
    op.drop_index(op.f("ix_programmes_support_status"), table_name="programmes")
    op.drop_table("programmes")
    op.drop_table("documents")
    # ### end Alembic commands ###
